### ISSUE TITLE
Dependency Fail - Flax

### ISSUE THREAD

**Issue by natestone** [natestone/yahtzotron#1]
yahtzotron play pretrained/yahtzee-score.pkl

```
Traceback (most recent call last):
  File "/Users/nate/.local/bin/yahtzotron", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/yahtzotron/cli.py", line 81, in play
    from yahtzotron.interactive import play_interactive
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/yahtzotron/interactive.py", line 6, in <module>
    from yahtzotron.agent import Yahtzotron
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/yahtzotron/agent.py", line 10, in <module>
    import haiku as hk
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/haiku/__init__.py", line 20, in <module>
    from haiku import experimental
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/haiku/experimental/__init__.py", line 66, in <module>
    from haiku.experimental import flax
  File "/Users/nate/.local/pipx/venvs/yahtzotron/lib/python3.13/site-packages/haiku/_src/no_flax.py", line 24, in __getattr__
    raise ImportError(
        '`haiku.experimental.flax` features require `flax` to be installed.'
    )
ImportError: `haiku.experimental.flax` features require `flax` to be installed.
```

**Comment by natestone** [comment]
Solving with 'pipx install flax'

Tested on Mac OS X.  Need to update dependency list for installer.

**Comment by natestone** [comment]
pipx install flax --include-deps

- Still doesn't work

**Comment by natestone** [comment]
brew install atlas

brew install openblas

brew install lapack

You can use this alternative route, if LD is not done automatically.

export DYLD_LIBRARY_PATH=/path/to/atlas/lib:$DYLD_LIBRARY_PATH

export DYLD_LIBRARY_PATH=/path/to/lapack/lib:$DYLD_LIBRARY_PATH

These environment variables should point to where the libraries are if they are in a different location.

**Comment by natestone** [comment]
export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"

For pkg-config to find openblas you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"

**Comment by natestone** [comment]
use python 3.10.4 

pyenv local 3.10.4

Install pyenv and python 3.10.4 before doing above steps.

**Comment by natestone** [comment]
in: /Users/nate/.pyenv/versions/3.10.6/include
MacBook-Air-M2:include nate$ ln -s /opt/homebrew/opt/openblas/include/* .

in: /Users/nate/.pyenv/versions/3.10.6/lib
MacBook-Air-M2:lib nate$ ln -s /opt/homebrew/opt/openblas/lib/* .

**Comment by natestone** [comment]
ln -s /opt/homebrew/Cellar/lapack/3.12.0/lib/* .

**Comment by natestone** [comment]
use pypi-timemachine

**Comment by natestone** [comment]
MacBook-Air-M2:yahtzotron nate$ /Users/nate/.pyenv/shims/pypi-timemachine 2021-11-01
Starting pypi-timemachine server at http://localhost:60198
pip install --index-url http://127.0.0.1:

**Comment by natestone** [comment]
arrgh - https://github.com/ikostrikov/implicit_q_learning/issues/3

jax incompatible with 3.10

**Comment by natestone** [comment]
pip install --index-url http://127.0.0.1:60198 . --no-deps optax
Looking in indexes: http://127.0.0.1:60198
Processing /Users/nate/development/yahtzotron

**Comment by natestone** [comment]
brew install blas-devel lapack-devel
